config/routes.rb
Rails.application.routes.draw do

  match '', to: 'websites#index', constraints: {subdomain: /.+/}, :via => [:get]
  
    get '/home', to: 'websites#index', as: "website"
    get '/aboutus', to: 'websites#aboutus', as: "website_aboutus"
    get '/blog', to: 'websites#blog', as: "website_blog"
    get '/blogshow', to: 'websites#blogshow', as: "website_blogshow"
    get '/contact', to: 'websites#contact', as: "website_contact"

  devise_for :branches, :controllers => { registrations: 'registrations', sessions: 'sessions' } #override devise
  devise_for :admins

  get 'admins/dashboard'

  get 'branches/dashboard'
  get 'branches/settings'
  get 'branches/editwebsite'

  get 'admin/root' => "admins#dashboard" # devise login redirect
  get 'branch/root' => "branches#dashboard" # devise login redirect

  devise_scope :branch do
    get 'admins/newwebsite' => 'registrations#new'
  end

  root 'admins#dashboard'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/branch.rb
class Branch < ActiveRecord::Base
	has_one :website
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 accepts_nested_attributes_for :website
end

app/models/website.rb
class Website < ActiveRecord::Base
	belongs_to :branch
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!

  def dashboard
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
	before_action :authenticate_branch!
	layout 'branches'

  def dashboard
  	@branch = params[:id].blank? ? current_branch : Branch.find(params[:id])
  end

  def settings
  end

  def editwebsite
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_admin!
	prepend_before_filter :require_no_authentication, only: [ :cancel ]

  protected

  def sign_up(resource_name, resource)
  end

  private
 
  def sign_up_params
    params.require(:branch).permit(:branch, :email, :password, :password_confirmation, website_attributes: [:subdomain, :branch_id])
  end
 
  def account_update_params
    params.require(:branch).permit(:branch, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def new
  	@branches = Branch.all
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    yield resource if block_given?
    respond_with(resource, serialize_options(resource))
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  def index
    @website = Website.find_by_subdomain!(request.subdomain) 
  end

  def aboutus
    @website = Website.find_by_subdomain!(request.subdomain)
  end

  def blog
    @website = Website.find_by_subdomain!(request.subdomain) 
  end

  def blogshow
  end

  def contact
    @website = Website.find_by_subdomain!(request.subdomain) 
  end
end

app/helpers/admins_helper.rb
module AdminsHelper

def resource_name
	:branch
end

def resource
	@resource ||= Branch.new
end

def devise_mapping
	@devise_mapping ||= Devise.mappings[:branch]
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper

	def current_website_id
		@current = Website.find(params[:id])
		return @current.id
	end

end

app/views/admins/dashboard.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1 class="pageheader content">DASHBOARD</h1>
	</div>
</div>

<div class="row content padding2v">
	<div class="large-7 columns content row1">
		<div class="welcomebox padding3v content">
		<h3><span class="weight100">Welcome to your dashboard,</span><br><span class="weight600">Diamond Logistics Devon</span></h3>
		</div>
	</div>
	<div class="large-5 columns content row1">
		<div class="gradientradiusbox padding3v content padding3v row1">
		<p class="white">graph here</p>
		</div>
	</div>
</div>

<script type="text/javascript">
    (function() {
        $(function() {

          $(function() {
            $('.row1').matchHeight();
          });
          
        });
    })();
</script>


<!--<a href="<%= admins_newwebsite_path %>">Create new website</a> -->

app/views/branches/dashboard.html.erb
<h1>Dashboard</h1>
<p>your website is <%= link_to(@branch.website) do %><%= @branch.website.subdomain %><% end %></p>

app/views/branches/editwebsite.html.erb
<h1>Branches#edit</h1>
<p>Find me in app/views/branches/edit.html.erb</p>

app/views/branches/settings.html.erb
<h1>Branches#settings</h1>
<p>Find me in app/views/branches/settings.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Control Panel</title>
  <%= stylesheet_link_tag "admins" %>
  <%= javascript_include_tag "admins" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>
</head>
<body>

<div class="row headerrowgrey padding3h">
	<div class="icon-bar six-up">
	  <a class="item navcurrentarrow">
	    <%= image_tag('dashboardicon.png') %>
	    <label>DASHBOARD</label>
	  </a>
	  <a class="item">
	    <%= image_tag('analyticsicon.png') %>
	    <label>ANALYTICS</label>
	  </a>
	  <a class="item">
	    <%= image_tag('buildericon.png') %>
	    <label>BUILDER</label>
	  </a>
	  <a class="item">
	    <%= image_tag('mailingicon.png') %>
	    <label>MAILING LIST</label>
	  </a>
	  <a class="item">
	    <%= image_tag('leadboardicon.png') %>
	    <label>LEADERBOARD</label>
	  </a>
	  <a class="item">
	    <%= image_tag('settingsicon.png') %>
	    <label>SETTINGS</label>
	  </a>
	</div>
</div>

<div class="row padding3h">
	<div class="large-12 columns maincontent">
	<%= yield %>
	<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
	</div>
</div>


<script>
  $(document).foundation();
</script>

</body>
</html>

app/views/layouts/branches.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microsites</title>
  <%= stylesheet_link_tag "admins" %>
  <%= javascript_include_tag "admins" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row">
	<div class="large-1 medium-1 columns iconbar">
		<ul class="side-nav text-center">
		  <li><a href="<%= branches_dashboard_path %>">Dashboard</a></li>
		  <li><a href="<%= branches_settings_path %>">Settings</a></li>
		  <li><a href="<%= branches_editwebsite_path %>">Edit Website</a></li>
		  <li><a href="<%= branches_dashboard_path %>">Blog</a></li>
		  <li><a href="<%= branches_dashboard_path %>">Leaderboard</a></li>
		  <li><a href="<%= branches_dashboard_path %>"><% if branch_signed_in? %><%= current_branch.branch %><% end %></a></li>
		  <% if branch_signed_in? %>
			  <li><%= link_to('Sign out', destroy_branch_session_path, :method => :delete) %></li>
			  <% else %>
			  <li><%= link_to('Sign in', new_branch_session_path) %></li>
		  <% end %>
		</ul>
	</div>
	<div class="large-11 medium-11 columns">
		<% if flash[:notice] %>
		    <p id="notice" ><%= flash[:notice] %></p> 
		<% elsif flash[:alert] %>
		    <p id="alert" ><%= flash[:alert] %></p> 
		<% end %>
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microsites</title>
  <%= stylesheet_link_tag "admins" %>
  <%= javascript_include_tag "admins" %>
  <%= csrf_meta_tags %>
</head>
<body>

		<% if flash[:notice] %>
		    <p id="notice" ><%= flash[:notice] %></p> 
		<% elsif flash[:alert] %>
		    <p id="alert" ><%= flash[:alert] %></p> 
		<% end %>
		
		<%= yield %>

</body>
</html>

app/views/layouts/websites.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microsites</title>
  <%= stylesheet_link_tag controller_name %>
  <%= javascript_include_tag controller_name %>
  <%= csrf_meta_tags %>
</head>
<body>


		<%= yield %>

</body>
</html>

app/views/websites/aboutus.html.erb
	<div id="page">
		<div id="header">
			<div class="background">
				<h1><a href="index.html">DelliStore</a></h1>
				<h1 class="location"><%= @website.subdomain %></h1>
				<ul>
					<li><a href="<%= website_path %>">Home</a></li>
					<li class="active"><a href="<%= website_aboutus_path %>">About Us</a></li>
					<li><a href="<%= website_blog_path %>">Blog</a></li>
					<li><a href="<%= website_contact_path %>">Contact Us</a></li>
				</ul>
			</div>
		</div>
		<div id="content">
			<div id="leftcol">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<h2>About the <span>DelliStore!</span></h2>
						<p>liquam suscipit. <strong>Integer justo</strong> erat, bibendum sed, lacinia eu, tristique condimentum, magna. Aliquam augue dolor, tempus sit amet, pharetra nec, blandit elementum, diam. Proin pharetra odio eu lectus sollicitudin ultricies. Suspendisse turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti.</p>
						<div class="clear">
							<div class="border-left-top">
								<div class="border-right-top">
									<div class="border-left-bottom">
										<div class="border-right-bottom">
											<img src="img/img-interier.jpg" alt="Interier" />
										</div>
									</div>
								</div>
							</div>
						</div>
						<p>liquam suscipit. <strong>Integer justo</strong> erat, bibendum sed, lacinia eu, tristique condime ntum, magna. Aliquam augue dolor, tempus sit amet, pharetra nec.liquam suscipit. <strong>Integer justo</strong> erat, bibendum sed, lacinia eu, tristique condime ntum, magna. Aliquam augue dolor, tempus sit amet, pharetra nec.liquam suscipit. liquam su scipit. <strong>Integer justo</strong> erat, bibendum sed, lacinia eu, tristique condime ntum, magna.</p>
					</div>
					<div class="block-bottom"></div>
				</div>


			</div>
			<div id="rightcol">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<h3>The <span>Store!</span></h3>
						<ul>
							<li><a href="#">The History</a></li>
							<li><a href="#">Meet The Staff</a></li>
							<li><a href="#">Contacting Us</a></li>
						</ul>
					</div>
					<div class="block-bottom"></div>
				</div>
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<h3><span>Sign Up!</span></h3>
						<form id="signup-form" action="#">
							<fieldset>
								<label>Email Address</label>
								<input type="text" />
								<input class="submit" type="submit" value="Sing Up!" />
							</fieldset>
						</form>
					</div>
					<div class="block-bottom"></div>
				</div>
			</div>
		</div>
		<div id="footer">
			<p>©2009 The DelliStore. Design by <a href="http://www.dellustrations.com/templates.html">Dellustrations.com</a> for <a href="http://www.smashingmagazine.com">Smashing Magazine</a></p>
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About Us</a></li>
				<li><a href="services.html">Blog</a></li>
				<li><a href="contact.html">Contact us</a></li>
			</ul>
		</div>
	</div>

app/views/websites/blog.html.erb
	<div id="page">
		<div id="header">
			<div class="background">
				<h1><a href="index.html">DelliStore</a></h1>
				<h1 class="location"><%= @website.subdomain %></h1>
				<ul>
					<li class="active"><a href="<%= website_path %>">Home</a></li>
					<li><a href="<%= website_aboutus_path %>">About Us</a></li>
					<li><a href="<%= website_blog_path %>">Blog</a></li>
					<li><a href="<%= website_contact_path %>">Contact Us</a></li>
				</ul>
			</div>
		</div>
		<div id="content">
			<div id="leftcol">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<h2>Welcome to the <span>DelliStore!</span></h2>
							<p>
								<%= image_tag('img-cake.jpg', class: "cake") %>
								liquam suscipit. <strong>Integer justo</strong> erat, bibendum sed, lacinia eu, tristique condimentum, magna. Aliquam augue dolor, 
                                tempus sit amet, pharetra nec, blandit elementum, diam. Proin pharetra odio eu lectus sollicitudin ultricies. Suspend<br />
								isse turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti.</p>
						<a class="yellow-button" href="#"><span>Learn More</span></a>
					</div>
					<div class="block-bottom"></div>
				</div>
			</div>
			<div id="rightcol">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<h3>Our <span>Specials!</span></h3>
						<ul>
							<li><a href="#">Burger</a><strong>$4.99</strong></li>
							<li><a href="#">Chicken Wings</a><strong>$5.99</strong></li>
							<li><a href="#">French Fries</a><strong>$4.99</strong></li>
							<li><a href="#">Large Pizza</a><strong>$12.99</strong></li>
						</ul>
						<a class="yellow-button"><span>See Menu</span></a>
					</div>
					<div class="block-bottom"></div>
				</div>

	
			</div>
		</div>
		<div id="footer">
			<p>©2009 The DelliStore. Design by <a href="http://www.dellustrations.com/templates.html">Dellustrations.com</a> for <a href="http://www.smashingmagazine.com">Smashing Magazine</a></p>
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About Us</a></li>
				<li><a href="services.html">Blog</a></li>
				<li><a href="contact.html">Contact us</a></li>
			</ul>
		</div>
	</div>

app/views/websites/blogshow.html.erb
<h1>Websites#blogshow</h1>
<p>Find me in app/views/websites/blogshow.html.erb</p>

app/views/websites/contact.html.erb
	<div id="page">
		<div id="header">
			<div class="background">
				<h1><a href="index.html">DelliStore</a></h1>
				<h1 class="location"><%= @website.subdomain %></h1>
				<ul>
					<li><a href="<%= website_path %>">Home</a></li>
					<li><a href="<%= website_aboutus_path %>">About Us</a></li>
					<li><a href="<%= website_blog_path %>">Blog</a></li>
					<li class="active"><a href="<%= website_contact_path %>">Contact Us</a></li>
				</ul>
			</div>
		</div>
		<div id="content">
			<div id="leftcol">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<h2>Contact the <span>DelliStore!</span></h2>
						<p>liquam suscipit. <strong>Integer justo</strong> erat, bibendum sed, lacinia eu, tristique condimentum, magna. Aliquam augue dolor, tempus sit amet, pharetra nec, blandit elementum, diam. Proin pharetra odio eu lectus sollicitudin ultricies.</p>
						<form id="contact-form" action="#">
							<fieldset>
								<ul>
									<li>
										<label>Full Name <span>*</span></label>
										<input type="text" />
									</li>
									<li>
										<label>Email Address <span>*</span></label>
										<input type="text" />
									</li>
									<li>
										<label>Your Message  <span>*</span></label>
										<textarea cols="50" rows="5"></textarea>
									</li>
									<li class="submit">
										<p><span>*</span> These are required fields</p>
										<input type="submit" value="Send Message"/>
									</li>
								</ul>
							</fieldset>
						</form>
					</div>
					<div class="block-bottom"></div>
				</div>
			</div>
			<div id="rightcol">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<h3>The <span>Store!</span></h3>
						<ul>
							<li><a href="#">The History</a></li>
							<li><a href="#">Meet The Staff</a></li>
							<li><a href="#">Contacting Us</a></li>
							<li><a href="#">Hours of Operation</a></li>
						</ul>
					</div>
					<div class="block-bottom"></div>
				</div>
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<h3><span>Get it Free!</span></h3>
						<div class="free-cake">
							<img src="img/img-cake-small.jpg" alt="Cake" />
							<p>Get Your <strong>FREE Cake!</strong></p>
							<a class="yellow-button"><span>Get It!</span></a>
						</div>
					</div>
					<div class="block-bottom"></div>
				</div>
			</div>
		</div>
		<div id="footer">
			<p>©2009 The DelliStore. Design by <a href="http://www.dellustrations.com/templates.html">Dellustrations.com</a> for <a href="http://www.smashingmagazine.com">Smashing Magazine</a></p>
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About Us</a></li>
				<li><a href="services.html">Blog</a></li>
				<li><a href="contact.html">Contact us</a></li>
			</ul>
		</div>
	</div>

app/views/websites/index.html.erb
	<div id="page">
		<div id="header">
			<div class="background">
				<h1><a href="index.html">DelliStore</a></h1>
				<h1 class="location"><%= @website.subdomain %></h1>
				<ul>
					<li class="active"><a href="<%= website_path %>">Home</a></li>
					<li><a href="<%= website_aboutus_path %>">About Us</a></li>
					<li><a href="<%= website_blog_path %>">Blog</a></li>
					<li><a href="<%= website_contact_path %>">Contact Us</a></li>
				</ul>
			</div>
		</div>
		<div id="content">
			<div id="leftcol">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<h2>Welcome to the <span>DelliStore!</span></h2>
							<p>
								<%= image_tag('img-cake.jpg', class: "cake") %>
								liquam suscipit. <strong>Integer justo</strong> erat, bibendum sed, lacinia eu, tristique condimentum, magna. Aliquam augue dolor, 
                                tempus sit amet, pharetra nec, blandit elementum, diam. Proin pharetra odio eu lectus sollicitudin ultricies. Suspend<br />
								isse turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti.</p>
						<a class="yellow-button" href="#"><span>Learn More</span></a>
					</div>
					<div class="block-bottom"></div>
				</div>
			</div>
			<div id="rightcol">
				<div class="block">
					<div class="block-top"></div>
					<div class="block-content">
						<h3>Our <span>Specials!</span></h3>
						<ul>
							<li><a href="#">Burger</a><strong>$4.99</strong></li>
							<li><a href="#">Chicken Wings</a><strong>$5.99</strong></li>
							<li><a href="#">French Fries</a><strong>$4.99</strong></li>
							<li><a href="#">Large Pizza</a><strong>$12.99</strong></li>
						</ul>
						<a class="yellow-button"><span>See Menu</span></a>
					</div>
					<div class="block-bottom"></div>
				</div>

	
			</div>
		</div>
		<div id="footer">
			<p>©2009 The DelliStore. Design by <a href="http://www.dellustrations.com/templates.html">Dellustrations.com</a> for <a href="http://www.smashingmagazine.com">Smashing Magazine</a></p>
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About Us</a></li>
				<li><a href="services.html">Blog</a></li>
				<li><a href="contact.html">Contact us</a></li>
			</ul>
		</div>
	</div>